(define (swaper list1 i j)
  (define (swaper-helper list1 i j n)
    (if(= n (length list1))
       '()
       (if(= n i)
          (cons (nth-element list1 j) (swaper-helper list1 i j (+ n 1)))
          (if(= n j)
             (cons (nth-element list1 i) (swaper-helper list1 i j (+ n  1)))
             (cons (nth-element list1 n) (swaper-helper list1 i j (+ n 1)))))))
  (swaper-helper list1 i j 0))
(define (swap matrix i j)
  (map (lambda(row) (swaper row i j)) matrix))
