(define (without-last list1)
  (if (= (length list1) 1)
      '()
      (cons (car list1) (without-last (cdr list1)))))
(define (duplicate-helper list1)
  (append list1 (without-last list1)))
(define (duplicate matrix1)
  (if (null? matrix1)
      '()
      (cons (duplicate-helper (car matrix1)) (duplicate (cdr matrix1)))))